[workspace]
authors = ["jonahctuttle <jonahctuttle@gmail.com>"]
channels = ["conda-forge"]
name = "blue-bikes-analysis(me)"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
marimo = ">=0.16.5,<0.17"
httpx = ">=0.28.1,<0.29"
polars = ">=1.34.0,<2"
beautifulsoup4 = ">=4.14.2,<5"
